version: "3"
services:
  webserver:
    build: .
    image: docker-plainkit
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./kirbycms:/var/www/html/
      - ./dockerconfig/php.ini:/etc/php/7.4/apache2/php.ini
    env_file:
      - ./dockerconfig/id.env
