title: Website

columns:
  left:
    width: 1/2
    sections:
      pages:
        label: alle Seiten
        type: pages
        status: all
  right:
    width: 1/2
    sections:
      meta:
        type: fields
        fields:
          deploy:
            type: webhook
            label: Deploy Production Site
            hook: production
            debug: false
          sitetitle:
            label: Seitentitel
            type: text
            width: 1/2
          metaauthor:
            label: Meta Autor:in
            type: text
            width: 1/2
          metakeywords:
            label: Keywords
            type: structure
            fields:
              keyword:
                label: Keyword
                type: text
          footer:
            label: Footer
            type: textarea
            size: small
            width: 1/2
          footercopyright:
            label: Footer Copyright
            type: textarea
            size: small
            width: 1/2
