name: CI

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set environment variable for deployment
        run: |
          echo "dest=${{secrets.DEPLOY_HOST}}" >> $GITHUB_ENV

      - name: sync Kirby
        run: |
          cd ./kirbycms
          composer install
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
            chmod 600 ./deploy_key
            rsync --exclude-from="rsync_exclude.txt" -chav --delete \
              -e 'ssh -p 22 -i ./deploy_key -o StrictHostKeyChecking=no' \
              ./ $dest
